// Activity Orchestrator Service
// Connects to Gemini AI first with seamless fallback to enriched Sri Lanka catalog

const geminiActivityService = require("./geminiActivityService");
const activityImageService = require("./activityImageService");

const curatedActivitiesCatalog = {
  ella: [
    {
      id: "act-nine-arch",
      title: "Nine Arch Bridge & Blue Train Spotting",
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 0,
      icon: "🚂",
      description: "Marvel at the British colonial stone viaduct as the scenic blue train rumbles through the lush jungle gorge.",
      highlight: "Best train crossings occur around 9:30 AM and 11:30 AM.",
      location: "Demodara, Ella",
      source: "catalog",
    },
    {
      id: "act-little-adams-peak",
      title: "Little Adam's Peak Sunrise Hike",
      category: "Hiking",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 0,
      icon: "🥾",
      description: "Gentle morning trail through rolling tea bushes rewarding you with 360-degree mountain panoramas of the Ella Gap.",
      highlight: "Start hike at 5:45 AM for magnificent golden hour colors.",
      location: "Passara Road, Ella",
      source: "catalog",
    },
    {
      id: "act-flying-ravana",
      title: "Flying Ravana Mega Zipline",
      category: "Adventure",
      timeSlot: "Afternoon",
      duration: "1.5 hours",
      cost: 7500,
      icon: "🦅",
      description: "Sri Lanka's first mega zipline soaring at 80 km/h over dramatic mountain ravines and lush forest canopy.",
      highlight: "Dual-wire setup allows two people to fly simultaneously.",
      location: "Little Adam's Peak Estate, Ella",
      source: "catalog",
    },
    {
      id: "act-ravana-falls",
      title: "Ravana Falls & Natural Pool Dip",
      category: "Nature",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 0,
      icon: "💧",
      description: "Legendary 25-meter multi-tiered waterfall cascading down steep limestone rocks, perfect for scenic photo stops.",
      highlight: "Wear sturdy shoes as the rocks near the lower pool can be slippery.",
      location: "Wellawaya Road, Ella",
      source: "catalog",
    },
    {
      id: "act-tea-factory",
      title: "Halpewatte Tea Factory & Tasting Tour",
      category: "Culture",
      timeSlot: "Morning",
      duration: "1.5 hours",
      cost: 1500,
      icon: "🍵",
      description: "Step inside the Uva region's largest tea factory to witness traditional withering, rolling, and grade tasting.",
      highlight: "Includes tasting session of premium Orange Pekoe teas.",
      location: "Badulla Road, Ella",
      source: "catalog",
    },
    {
      id: "act-ella-rock",
      title: "Ella Rock Challenging Summit Trek",
      category: "Hiking",
      timeSlot: "Morning",
      duration: "4 hours",
      cost: 0,
      icon: "⛰️",
      description: "Rewarding trek starting along the railway tracks, crossing eucalyptus forests to a cliff precipice overlooking the valley.",
      highlight: "Hire a local guide or download offline trail maps as paths branch frequently.",
      location: "Ella Railway Station Trailhead",
      source: "catalog",
    },
  ],

  mirissa: [
    {
      id: "act-mirissa-whale",
      title: "Blue Whale Watching Yacht Cruise",
      category: "Nature",
      timeSlot: "Morning",
      duration: "4.5 hours",
      cost: 12000,
      icon: "🐋",
      description: "Morning boat excursion into deep oceanic trenches where magnificent blue whales and spinner dolphins surface.",
      highlight: "Peak sightings between November and April; take motion sickness pills before boarding.",
      location: "Mirissa Fishery Harbour",
      source: "catalog",
    },
    {
      id: "act-coconut-hill",
      title: "Coconut Tree Hill Golden Hour Walk",
      category: "Sightseeing",
      timeSlot: "Evening",
      duration: "1.5 hours",
      cost: 0,
      icon: "🌴",
      description: "Iconic oceanfront cliff mound crowned with towering palm trees overlooking the azure bay waves.",
      highlight: "Visit 45 minutes before sunset for the best lighting without midday crowds.",
      location: "Bandaramulla, Mirissa",
      source: "catalog",
    },
    {
      id: "act-weligama-surf",
      title: "Beginner Surfing Lesson at Weligama Bay",
      category: "Adventure",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 4500,
      icon: "🏄",
      description: "Learn to catch gentle, rolling sandy-bottom waves with an ISA-certified local instructor.",
      highlight: "Includes surfboard hire, rash guard, and beach safety guidance.",
      location: "Weligama Main Beach",
      source: "catalog",
    },
    {
      id: "act-secret-beach",
      title: "Secret Beach Snorkeling & Day Relaxation",
      category: "Beaches",
      timeSlot: "Afternoon",
      duration: "3 hours",
      cost: 0,
      icon: "🏖️",
      description: "Secluded cove with calm coral reef lagoons, palm shade, and a chilled-out beach shack bar.",
      highlight: "Accessible by tuk-tuk or a short scenic trail through coconut groves.",
      location: "Secret Beach, Mirissa",
      source: "catalog",
    },
    {
      id: "act-parrot-rock",
      title: "Parrot Rock Tidal Reef Walk",
      category: "Sightseeing",
      timeSlot: "Evening",
      duration: "1 hour",
      cost: 0,
      icon: "🦜",
      description: "Walk out along the sand spit at low tide to climb this red rock outcrop for panoramic Mirissa Bay vistas.",
      highlight: "Only cross during low tide when the sandbar is fully exposed.",
      location: "Mirissa Beach Center",
      source: "catalog",
    },
    {
      id: "act-koggala-stilt",
      title: "Traditional Stilt Fishermen Cultural Stop",
      category: "Culture",
      timeSlot: "Morning",
      duration: "1 hour",
      cost: 1000,
      icon: "🎣",
      description: "Observe the centuries-old traditional fishing technique perched atop wooden poles planted in the coastal reef.",
      highlight: "Early morning or late afternoon offers timeless silhouette photo opportunities.",
      location: "Ahangama Coastal Road",
      source: "catalog",
    },
  ],

  galle: [
    {
      id: "act-galle-ramparts",
      title: "UNESCO Galle Fort Ramparts Sunset Walk",
      category: "Sightseeing",
      timeSlot: "Evening",
      duration: "2 hours",
      cost: 0,
      icon: "🏰",
      description: "Stroll along 17th-century Dutch fortress ramparts as the sun dips into the Indian Ocean at Flag Rock.",
      highlight: "Watch local cliff divers leap into the churning ocean swells at Flag Rock.",
      location: "Galle Fort, Church Street",
      source: "catalog",
    },
    {
      id: "act-galle-lighthouse",
      title: "Galle Lighthouse & Point Utrecht Bastion",
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "1.5 hours",
      cost: 0,
      icon: "🗼",
      description: "Sri Lanka's oldest operating lighthouse standing majestic beneath swaying coconut palms.",
      highlight: "Scenic sandy cove right beside the lighthouse is great for wading.",
      location: "Rampart Street, Galle Fort",
      source: "catalog",
    },
    {
      id: "act-jungle-beach",
      title: "Unawatuna Jungle Beach & Coral Reef Snorkel",
      category: "Beaches",
      timeSlot: "Morning",
      duration: "3 hours",
      cost: 0,
      icon: "🐠",
      description: "Hidden twin-cove beach surrounded by lush coastal forest teeming with colorful reef fish and turtles.",
      highlight: "Bring snorkeling gear to explore the natural coral reef 30 meters offshore.",
      location: "Rumassala Hill, Unawatuna",
      source: "catalog",
    },
    {
      id: "act-dutch-hospital",
      title: "Old Dutch Hospital Shopping & Dining",
      category: "Food",
      timeSlot: "Evening",
      duration: "2 hours",
      cost: 3500,
      icon: "🍤",
      description: "Colonial arcade overlooking the ocean featuring curated gem boutiques and fresh seafood restaurants.",
      highlight: "Sample fresh butter garlic lagoon crab with chilled Ceylon ginger beer.",
      location: "Hospital Street, Galle Fort",
      source: "catalog",
    },
    {
      id: "act-maritime-museum",
      title: "National Maritime Archaeology Museum",
      category: "Culture",
      timeSlot: "Afternoon",
      duration: "1.5 hours",
      cost: 1200,
      icon: "⚓",
      description: "Discover artifacts recovered from ancient shipwrecks along the southern Silk Route in a restored Dutch warehouse.",
      highlight: "Features life-sized diorama exhibits of traditional Sri Lankan naval navigation.",
      location: "Old Dutch Warehouse, Galle Fort",
      source: "catalog",
    },
  ],

  kandy: [
    {
      id: "act-tooth-temple",
      title: "Temple of the Sacred Tooth Relic (Sri Dalada Maligawa)",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 2000,
      icon: "🛕",
      description: "Venerated royal palace complex housing the sacred tooth of the Buddha with elaborate golden shrines and drum rituals.",
      highlight: "Witness the morning Thevava pooja offering ceremony at 9:30 AM with traditional drummers.",
      location: "Kandy Royal Palace Complex",
      source: "catalog",
    },
    {
      id: "act-peradeniya",
      title: "Royal Botanical Gardens of Peradeniya",
      category: "Nature",
      timeSlot: "Morning",
      duration: "3 hours",
      cost: 3000,
      icon: "🌺",
      description: "Spectacular 147-acre garden renowned for its avenue of royal palms, giant Javan fig tree, and orchid pavilion.",
      highlight: "Visit the Orchid House featuring more than 300 exotic hybrid varieties.",
      location: "Peradeniya, 5km from Kandy",
      source: "catalog",
    },
    {
      id: "act-kandy-lake",
      title: "Kandy Lake Scenic Walk & Viewpoint",
      category: "Sightseeing",
      timeSlot: "Evening",
      duration: "1.5 hours",
      cost: 0,
      icon: "🦢",
      description: "Peaceful stroll along the decorative Cloud Wall (Walakulu Bamma) with mountain reflections in the mirror-like waters.",
      highlight: "Head up to Arthur's Seat viewpoint for a bird's eye vista across the lake and town.",
      location: "Kandy Lake Promenade",
      source: "catalog",
    },
    {
      id: "act-kandyan-dance",
      title: "Traditional Kandyan Cultural Dance & Fire Walking",
      category: "Culture",
      timeSlot: "Evening",
      duration: "1.5 hours",
      cost: 2500,
      icon: "🔥",
      description: "Vibrant showcase of athletic drumming, elaborate brass headdresses, acrobatic leaps, and barefoot fire-walking.",
      highlight: "Shows start promptly at 5:00 PM; arrive 20 minutes early for front-row seats.",
      location: "Kandy Lake Club",
      source: "catalog",
    },
    {
      id: "act-bahirawakanda",
      title: "Bahirawakanda Vihara Giant Buddha Ascent",
      category: "Sightseeing",
      timeSlot: "Afternoon",
      duration: "1.5 hours",
      cost: 500,
      icon: "🧘",
      description: "Towering 88-foot white Buddha statue seated high on a hilltop watching over the entire valley.",
      highlight: "Climb the stairs behind the statue for panoramic views of the Knuckles mountain range.",
      location: "Bahirawakanda Hill, Kandy",
      source: "catalog",
    },
  ],

  sigiriya: [
    {
      id: "act-lion-rock",
      title: "Sigiriya Lion Rock Ancient Fortress Ascent",
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "3 hours",
      cost: 11500,
      icon: "🦁",
      description: "Climb King Kashyapa's 5th-century palace built atop a 200m monolithic rock featuring ancient frescoes and mirror wall.",
      highlight: "Start climb at 7:00 AM sharp to avoid midday heat and steep stair bottlenecks.",
      location: "Sigiriya Heritage Site",
      source: "catalog",
    },
    {
      id: "act-pidurangala",
      title: "Pidurangala Rock Sunrise Hike",
      category: "Hiking",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 1000,
      icon: "🌄",
      description: "Scenic climb through an ancient cave temple to an expansive flat summit offering an iconic direct view of Sigiriya Rock.",
      highlight: "Bring a flashlight for the early 5:15 AM start; final 15 minutes involve mild boulder scrambling.",
      location: "Pidurangala Trailhead",
      source: "catalog",
    },
    {
      id: "act-dambulla-caves",
      title: "Dambulla Golden Rock Cave Temples",
      category: "Culture",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 2500,
      icon: "🛕",
      description: "UNESCO World Heritage monastic cave complex containing 153 Buddha statues and stunning ceiling mural frescoes.",
      highlight: "Shoulders and knees must be covered; socks recommended for walking on hot sunlit stone.",
      location: "Dambulla Town, 15km from Sigiriya",
      source: "catalog",
    },
    {
      id: "act-minneriya-safari",
      title: "Minneriya Elephant Gathering Jeep Safari",
      category: "Nature",
      timeSlot: "Afternoon",
      duration: "4 hours",
      cost: 14000,
      icon: "🐘",
      description: "Open-top 4x4 safari witnessing herds of over 100 wild elephants feeding and bathing around the ancient reservoir.",
      highlight: "Best wildlife viewing is between 3:30 PM and 6:30 PM as elephants assemble on the grass.",
      location: "Minneriya National Park",
      source: "catalog",
    },
    {
      id: "act-hiriwadunna-village",
      title: "Hiriwadunna Traditional Village & Catamaran Ride",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 4000,
      icon: "🛶",
      description: "Bullock cart journey through paddy fields followed by a twin-hull catamaran boat cruise and authentic clay-pot lunch.",
      highlight: "Enjoy hands-on preparation of coconut sambol and fresh hoppers with village hosts.",
      location: "Hiriwadunna Village, Habarana",
      source: "catalog",
    },
  ],

  colombo: [
    {
      id: "act-gangaramaya",
      title: "Gangaramaya Temple & Seema Malaka Lake Shrine",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 1000,
      icon: "🏛️",
      description: "Eclectic temple complex featuring brass artifacts, antique cars, relic chambers, and a floating meditation pavilion.",
      highlight: "Seema Malaka pavilion on Beira Lake was redesigned by master architect Geoffrey Bawa.",
      location: "Sri Jinarathana Road, Colombo 02",
      source: "catalog",
    },
    {
      id: "act-galle-face",
      title: "Galle Face Green Sunset Stroll & Street Food Feast",
      category: "Food",
      timeSlot: "Evening",
      duration: "2 hours",
      cost: 1500,
      icon: "🌯",
      description: "Sprawling oceanfront promenade where locals fly kites, feel the sea breeze, and savor sizzling street food.",
      highlight: "Try crispy isso wade (spiced shrimp fritters) and freshly chopped cheese kottu roti.",
      location: "Galle Face Centre Road, Colombo 03",
      source: "catalog",
    },
    {
      id: "act-national-museum",
      title: "National Museum of Colombo & Royal Regalia",
      category: "Culture",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 1500,
      icon: "👑",
      description: "Housed in a grand 1877 Italianate palace displaying the jewel-encrusted throne and crown of the last King of Kandy.",
      highlight: "Walk across the adjacent leafy Viharamahadevi Park afterward.",
      location: "Albert Crescent, Colombo 07",
      source: "catalog",
    },
    {
      id: "act-pettah-market",
      title: "Pettah Bazaar Walking Tour & Red Mosque",
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 0,
      icon: "🕌",
      description: "Bustling labyrinth of trade streets lined with spice merchants, textiles, and the candy-striped Jami Ul-Alfar Mosque.",
      highlight: "Step inside the courtyard of the Red Mosque; visiting hours welcome respectful travelers.",
      location: "Main Street, Pettah, Colombo 11",
      source: "catalog",
    },
  ],

  "nuwara eliya": [
    {
      id: "act-pedro-tea",
      title: "Pedro Estate Tea Plucking & Factory Experience",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 1200,
      icon: "🌱",
      description: "Walk alongside skilled tea pluckers across misty hillside terraces and tour the 1885 artisan tea machinery.",
      highlight: "Sample a fresh cup of light, floral 'Ceylon Champagne' tea on the estate veranda.",
      location: "Pedro Tea Estate, Nuwara Eliya",
      source: "catalog",
    },
    {
      id: "act-horton-plains",
      title: "Horton Plains National Park & World's End Hike",
      category: "Hiking",
      timeSlot: "Morning",
      duration: "4.5 hours",
      cost: 11000,
      icon: "🌁",
      description: "Trek across cloud-forest plateaus to a sheer 870-meter cliff drop offering views stretching all the way to the southern ocean.",
      highlight: "Enter before 7:00 AM; mist typically rolls in by 10:00 AM obscuring the cliff drop.",
      location: "Horton Plains, Ohiya Trailhead",
      source: "catalog",
    },
    {
      id: "act-gregory-lake",
      title: "Gregory Lake Boating & Waterside Cycling",
      category: "Nature",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 1500,
      icon: "🚣",
      description: "Scenic highland lake surrounded by pine-clad slopes, horse riding tracks, swan pedal boats, and waterside cafes.",
      highlight: "Rent a bicycle for a relaxing lap around the paved lakeshore perimeter.",
      location: "Peradeniya-Badulla Highway, Nuwara Eliya",
      source: "catalog",
    },
    {
      id: "act-lovers-leap",
      title: "Lovers Leap Waterfall & Tea Trail",
      category: "Nature",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 0,
      icon: "💦",
      description: "Picturesque 30-meter single-drop waterfall originating from the slopes of Sri Lanka's tallest peak, Mount Pidurutalagala.",
      highlight: "Gentle 1.5km walk through tea fields starting near the Pedro estate manager's bungalow.",
      location: "Havilland Estate, Nuwara Eliya",
      source: "catalog",
    },
  ],

  trincomalee: [
    {
      id: "act-pigeon-island",
      title: "Pigeon Island National Park Snorkeling Adventure",
      category: "Adventure",
      timeSlot: "Morning",
      duration: "4 hours",
      cost: 10000,
      icon: "🤿",
      description: "Take a speedboat to an offshore marine national park teeming with blacktip reef sharks, sea turtles, and pristine live coral.",
      highlight: "Blacktip reef sharks here are docile and routinely swim within meters of snorkelers.",
      location: "Nilaveli Beach Boat Launch",
      source: "catalog",
    },
    {
      id: "act-koneswaram",
      title: "Koneswaram Hindu Kovil & Swami Rock Clifftop",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 0,
      icon: "🔱",
      description: "Vibrant sacred Hindu shrine perched atop a dramatic 130m sheer cliff known as Lovers' Leap overlooking Trincomalee Bay.",
      highlight: "Spot resident spotted deer roaming freely around the Portuguese Fort Frederick entrance.",
      location: "Fort Frederick, Trincomalee",
      source: "catalog",
    },
    {
      id: "act-nilaveli-beach",
      title: "Nilaveli Beach Relaxation & Fresh Seafood",
      category: "Beaches",
      timeSlot: "Afternoon",
      duration: "3 hours",
      cost: 0,
      icon: "🏖️",
      description: "Kilometers of powdery white sand with crystal-clear turquoise waters and serene, uncrowded beachfront cabanas.",
      highlight: "Feast on freshly grilled jumbo prawns at beachfront shack cafes.",
      location: "Nilaveli Coastal Strip",
      source: "catalog",
    },
  ],

  jaffna: [
    {
      id: "act-nallur-kovil",
      title: "Nallur Kandaswamy Kovil Temple Visit",
      category: "Culture",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 0,
      icon: "🛕",
      description: "Experience the spiritual grandeur of Jaffna's most sacred Hindu temple featuring magnificent golden gopurams and sacred puja rituals.",
      highlight: "Men must remove shirts to enter; morning puja at 8:00 AM is spectacular.",
      location: "Point Pedro Road, Nallur, Jaffna",
      source: "catalog",
    },
    {
      id: "act-jaffna-fort",
      title: "Jaffna Dutch Fort Coastal Ramparts Exploration",
      category: "Sightseeing",
      timeSlot: "Afternoon",
      duration: "2 hours",
      cost: 0,
      icon: "🏰",
      description: "Walk the massive star-shaped coral ramparts built by Portuguese and Dutch colonizers overlooking the shallow Jaffna lagoon.",
      highlight: "Visit around 5:00 PM to catch breathtaking sunset colors across the lagoon waters.",
      location: "Beach Road, Jaffna",
      source: "catalog",
    },
    {
      id: "act-casuarina-beach",
      title: "Casuarina Beach & Karainagar Island Excursion",
      category: "Beaches",
      timeSlot: "Afternoon",
      duration: "3.5 hours",
      cost: 500,
      icon: "🏖️",
      description: "Relax on soft white sand shores framed by whispy casuarina trees with crystal-clear, calm, and shallow wading waters.",
      highlight: "Drive across the scenic Karainagar Causeway linking the island to mainland Jaffna.",
      location: "Karainagar Island, Jaffna Peninsula",
      source: "catalog",
    },
    {
      id: "act-nagadeepa-temple",
      title: "Nagadeepa Purana Viharaya & Nainativu Island Ferry",
      category: "Culture",
      timeSlot: "Morning",
      duration: "4 hours",
      cost: 500,
      icon: "⛵",
      description: "Take a scenic public ferry boat to Nainativu Island to visit the ancient Buddhist shrine where Lord Buddha is said to have visited.",
      highlight: "Boats depart regularly from Kurikadduwan (KKD) jetty at the tip of the causeways.",
      location: "Nainativu Island, Jaffna",
      source: "catalog",
    },
    {
      id: "act-jaffna-library",
      title: "Jaffna Public Library & Clock Tower Architecture Tour",
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "1.5 hours",
      cost: 0,
      icon: "🏛️",
      description: "Admire the Indo-Saracenic neoclassical architectural splendor of Asia's most historically celebrated public library.",
      highlight: "Respect visitor guidelines and quiet reading hours during weekday mornings.",
      location: "Kandy Road, Jaffna",
      source: "catalog",
    },
    {
      id: "act-rio-ice-cream",
      title: "Iconic Rio Ice Cream & Jaffna Market Tasting Walk",
      category: "Culture",
      timeSlot: "Afternoon",
      duration: "1.5 hours",
      cost: 1000,
      icon: "🍨",
      description: "Indulge in famous local sundae creations at Rio Ice Cream and stroll through vibrant market stalls selling Palmyrah sweets and Jaffna spices.",
      highlight: "Try the signature Special Sundae topped with fruit and jelly cubes.",
      location: "Point Pedro Road, Nallur, Jaffna",
      source: "catalog",
    },
  ],
};

// Generic Fallback Activities for any Sri Lankan Destination
function getGenericActivities(destName) {
  const cap = destName.charAt(0).toUpperCase() + destName.slice(1);
  return [
    {
      id: `${destName.toLowerCase()}-city-discovery`,
      title: `${cap} Town Heritage & Market Walk`,
      category: "Sightseeing",
      timeSlot: "Morning",
      duration: "2 hours",
      cost: 0,
      icon: "🏛️",
      description: `Explore the vibrant local markets, colonial streets, and authentic cultural landmarks of ${cap}.`,
      highlight: "Early morning offers the best atmosphere when fresh produce arrives.",
      location: `${cap} Center`,
      source: "catalog",
    },
    {
      id: `${destName.toLowerCase()}-nature-trail`,
      title: `${cap} Scenic Nature & Viewpoint Hike`,
      category: "Nature",
      timeSlot: "Morning",
      duration: "2.5 hours",
      cost: 0,
      icon: "🌿",
      description: `Breathtaking outdoor walking trail through scenic natural landscapes and panoramic viewpoints in ${cap}.`,
      highlight: "Carry plenty of water and wear good walking footwear.",
      location: `Highlands of ${cap}`,
      source: "catalog",
    },
    {
      id: `${destName.toLowerCase()}-food-tour`,
      title: `${cap} Authentic Sri Lankan Food & Spice Trail`,
      category: "Food",
      timeSlot: "Evening",
      duration: "2 hours",
      cost: 2000,
      icon: "🍛",
      description: `Taste freshly prepared local rice and curry, hoppers, and traditional sweets at popular eateries in ${cap}.`,
      highlight: "Ask for 'mild spice' if you are sensitive to chili.",
      location: `${cap} Main Bazaar`,
      source: "catalog",
    },
    {
      id: `${destName.toLowerCase()}-cultural-shrine`,
      title: `${cap} Historic Temple & Sacred Ground Visit`,
      category: "Culture",
      timeSlot: "Afternoon",
      duration: "1.5 hours",
      cost: 500,
      icon: "🛕",
      description: `Serene visit to an ancient local temple with sacred Bodhi trees, prayer flags, and peaceful courtyards.`,
      highlight: "Remove shoes and hats prior to entering temple premises.",
      location: `Sacred District, ${cap}`,
      source: "catalog",
    },
  ];
}

function getFallbackActivities(destination) {
  const destKey = (destination || "").toLowerCase().trim();
  const found = Object.keys(curatedActivitiesCatalog).find(
    (k) => destKey.includes(k) || k.includes(destKey)
  );

  const rawList = found ? curatedActivitiesCatalog[found] : getGenericActivities(destination || "Sri Lanka");

  return rawList.map((act) => ({
    ...act,
    image: act.image || activityImageService.getActivityPhoto(act.title, act.description, act.category, act.imageTag),
  }));
}

// Master Activity Orchestrator
async function getActivities({ destination, budget, tripType, travelers, category, exclude }) {
  // 1. Check Gemini AI Provider first
  if (process.env.GEMINI_API_KEY) {
    try {
      console.log(`[ActivityService] Querying Gemini AI for real activities in: ${destination}`);
      const geminiActivities = await geminiActivityService.fetchActivitiesWithGemini({
        destination,
        budget: budget || 75000,
        tripType: tripType || "Solo",
        travelers: travelers || 1,
        category,
        exclude,
      });

      if (geminiActivities && geminiActivities.length > 0) {
        console.log(`[ActivityService] Successfully generated ${geminiActivities.length} live activities via Gemini AI`);
        return {
          provider: "gemini",
          activities: geminiActivities,
        };
      }
    } catch (err) {
      console.warn(`[ActivityService] Gemini AI fetch failed (${err.message}). Falling back to curated catalog.`);
    }
  }

  // 2. Fallback to Curated Catalog with Photos
  console.log(`[ActivityService] Using curated Sri Lanka activity catalog for: ${destination}`);
  let fallbackActivities = getFallbackActivities(destination);

  if (exclude) {
    const excludeList = (Array.isArray(exclude) ? exclude : exclude.split(","))
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean);

    if (excludeList.length > 0) {
      const filtered = fallbackActivities.filter(
        (a) =>
          !excludeList.includes((a.title || "").toLowerCase()) &&
          !excludeList.includes(a.id)
      );
      if (filtered.length > 0) {
        fallbackActivities = filtered;
      }
    }
  }

  const enrichedFallback = await activityImageService.enrichActivitiesWithPhotos(fallbackActivities, destination);

  return {
    provider: "catalog",
    activities: enrichedFallback,
  };
}

module.exports = {
  getActivities,
  getFallbackActivities,
};
